<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>
	<ItemGroup>
	  <AdditionalFiles Remove="Content\NewFolder\**" />
	  <Compile Remove="Content\NewFolder\**" />
	  <EmbeddedResource Remove="Content\NewFolder\**" />
	  <None Remove="Content\NewFolder\**" />
	</ItemGroup>

	<!-- References -->

</Project>